### ISSUE TITLE
No message is received for some countries when dataset created

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dataset-configuration#110]
The message is not sent depending on the countries chosen in the sharing settings.

I guess it has to do with the metadata of the countries. For instance, for countries that are actually used by NRC as Afganistan or Colombia, it seems to work fine. However when I choose Burundi o Chad no confirmation or error message is received.

I am using admin user (which belongs to GL_GlobalAdministrator user group)

**Comment by tokland** [comment]
Cannot reproduce, let's discuss it on the meeting

**Comment by adrianq** [comment]
It seems to be a misconfiguration in my user. Seems to be solved!
