### ISSUE TITLE
Enhance Multiselect

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dataset-configuration#112]
- [x] Double check and integrate what we currently have
- [x] Improve multiselect feature
   - [x] Add checkbox on the left
   - [ ] Select All/None

**Comment by tokland** [comment]
Preliminary work done at branch (no PR yet): feature/112-multiselect

Now you can multiselect using control  + click. Pending: select column

Moving to backlog until we come back to bulk actions
