### ISSUE TITLE
find a better place for 'group data elements in sections'

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dataset-configuration#119]
I guess the natural place would be in the sections tab (step 4) but this may need to reload this tab and I am not sure about how complex it would be...

**Comment by tokland** [comment]
Makes sense. Being React, it should be pretty painless.

**Comment by adrianq** [comment]
If so, can we go for this before starting with the context actions?

**Comment by tokland** [comment]
Sure. Any idea where to put the boolean in the UI? Within the 3 dots would be clean but not sure since those settings are section-scoped.

**Comment by adrianq** [comment]
Yes, I thought exactly the same. Conceptually they are completely different... and they are not filters either. mmmm would it be too difficult to split the 'paper' that shows up when you click on the 3 dots in two? So that we create two sections in the 3 dots. Otherwise just added to the right of the filters and we can move it later on. This layout is becoming a bit too much and we may need to organise it in a different way but we can revisit it in the future.

**Comment by tokland** [comment]
I started it simple: within the popover, with a divider:

![dhis2-dsc-sections-popover](https://user-images.githubusercontent.com/24643/29313541-e7fe9e82-81ba-11e7-9a0f-b001db5960cf.png)
