### ISSUE TITLE
First steps: Investigate, analyse, update and prototype

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dataset-configuration#12]
Current configuration is using [development of dataset configuration repo](https://github.com/EyeSeeTea/dataset-configuration/tree/development) and [multiple_data_table branch of d2-ui](https://github.com/EyeSeeTea/d2-ui/tree/multiple_data_table)

d2-ui is based on 2.25 version while dataset-configuration is a mixed between 2.24 and 2.25. Dataset-configuration was originally developed based on this [react-skeleton](https://github.com/dhis2/app-skeleton) which is not maintained anymore. On the other hand, d2-ui branch contains some simple modifications in order to allow multiple row selection. Further information about the current behaviour can be found in [this PR](https://github.com/dhis2/d2-ui/pull/88).

Some ideas about how to proceed (although we can discuss them in detail tomorrow):
- [x] Set up environment
- [x] Update to target version 2.26 the app dependecies
- [x] Update d2-ui applying current changes for multiple selection
- [x] Update package.json and any minor improvement

When creating a new dataset a wizard will be guiding the user through the different steps. Currently, there is no wizard component in the d2-ui library. 
- [x] Investigate react wizard component. I googled for a few minutes and this is the only serious library I could find https://github.com/newbreedofgeek/react-stepzilla . Not sure if there is something we can reuse or better to do it ourselves. Anyway, it definitely worth a deeper search.
- [ ] Implement a prototype based on it

**Comment by adrianq** [comment]
@tokland Can not find the code in order to retrieve an npm dependency from a GitHub repo but [this is the idea](https://github.com/EyeSeeTea/d2-ui/blob/multiple_data_table/package.json#L51) or maybe it is as simple as publishing our own d2-ui version to npmjs. Not high priority though

**Comment by tokland** [comment]
Uploaded new v26 branches to those 2 repos:

https://github.com/eyeseetea/dataset-configuration/tree/v26-multiselect
https://github.com/eyeseetea/d2-ui/tree/v26-multiple-data-table

The upgrade to v26 was quite a work because of chained updates, specially material-ui@0.17

**Comment by tokland** [comment]
About the wizards:

== https://github.com/newbreedofgeek/react-stepzilla

  - Demo: https://newbreedofgeek.github.io/react-stepzilla/#
  - Features: Progress box + content box + previous/next buttons.
  - Last update: This week.

== https://github.com/react-component/steps

  - Demo: http://react-component.github.io/steps/examples/smallSize.html
  - Features: Only progress box (steps not linkable. Nice styling
  - Last update: This week
  
== https://github.com/jakubzloczewski/react-steps

  - Demo: http://jakubzloczewski.github.io/react-steps/
  - Features: Includes: only progress box (steps not linkable). Nice styling.
  - Last update: 6 months ago

== https://github.com/jacobrosenthal/react-wizard

  - Demo: https://jacobrosenthal.github.io/react-wizard/examples/data/index.html
  - Ugly styling.
  - Two years without updates
  - Few customizations
