### ISSUE TITLE
User Feedback

### ISSUE THREAD

**Issue by tokland** [EyeSeeTea/dataset-configuration#140]
Check platform or github issues (ws bridge?)

**Comment by tokland** [comment]
There lots of "customer feedback" platforms. I've tested http://idea.informer.com (100% free) and seems to work quite well. 

Project URL: http://nrc-dataset-configuration.idea.informer.com/proj/
User: nrcuser
Password: nrc1234

Tested here:

https://github.com/EyeSeeTea/dataset-configuration/tree/feature/140-user-feedback

![dhis2-feedback.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57022c2f494d000e00432e8e/125516c66e82c728ace21e0d46ec9c9330d0ceaf8aecbb41a55efbd665043761260ea62864c7b96aea1579000a5e4afe170d584caafd8878a6b73e708c5409e9c3714d36976345f3e5db55ea43a82a994e82bcbd8f4cc4ee3c26e08d864b3d1c1755.png)

**Comment by adrianq** [comment]
@ifoche you were also looking into this some time ago... Can you let us know what software you looked at by that time?

**Comment by adrianq** [comment]
Some references:
http://experiments.hertzen.com/jsfeedback/
https://github.com/niklasvh/html2canvas
https://stackoverflow.com/questions/4912092/using-html5-canvas-javascript-to-take-screenshots
https://www.google.com/tools/feedback/intl/en/learnmore.html#tab=step1-text
https://blog.jedox.com/screen-shot-web-via-javascript-saving-back-server/
https://www.npmjs.com/package/htmlshot

**Comment by tokland** [comment]
Check something with github gateway

**Comment by tokland** [comment]
It will need a bit of tweaking, but I've been able to post an issue with an screenshot using https://github.com/eisnerd/feedback-tool Let's discuss it on the next meeting.
