### ISSUE TITLE
Add disaggregation improvements

### ISSUE THREAD

**Issue by tokland** [EyeSeeTea/dataset-configuration#142]
- [x] Show in selector only catCombos with 1 category
- [x] Show hint text with categoryOptions on selected catCombo
- [x] Show hint on dropdown (MenuItem) with catOptions
- [x] Add text search for dataelements filtering  (#82)
- [x] Remove/hide "default" value for override.

Not fow now:
- [ ] Merge dis+grey steps
- [ ] Show icon + to create catCombo
- [ ] Multiple selection checkbox -> select applies all bulk.

**Comment by adrianq** [comment]
@tokland I have just added another task to the short term TODO list. I think it is clear but let me know if there is any doubt...

**Comment by tokland** [comment]
No "default", ok!

**Comment by tokland** [comment]
Material-ui selectors have no hover hints, but we can use standard html title attributes:
![Screenshot from 2017-09-07 11-07-51.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57022c2f494d000e00432e8e/125516c66e82c728ace21e0d46db978826878dba87e6ab03a24fff99691477227e49f3723dd5b468ee13365158424bad53444d04bea6d37ef5f22e7a98590cbf80385e70946b44abb0d41bbe52ba21894f83bebe8e5edcfa7f74b9dfd0126754505a9bf54f34a8934acd58f243e44a57a01a3563ef647b.png)
![Screenshot from 2017-09-07 11-08-00.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57022c2f494d000e00432e8e/125516c66e82c728ace21e0d46db978826878dba87e6ab03a24fff99691477227e49f3723dd5b468ee13365157424eac53444d04bea6d37ef5f22e7a98590cbf80385e70946b44abb0d41bbe52ba21894f83bebe8e5edcfa7f74b9dfd0126754505a9bf54f34a7934acd58f243e44a57a1103167e4647b.png)
