### ISSUE TITLE
Split "grey fields" to not scroll horizontally

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dataset-configuration#143]
![ta](https://user-images.githubusercontent.com/6850223/29815019-2b00c48e-8ca7-11e7-90de-0f4ea7d00791.png)

**Comment by adrianq** [comment]
@tokland If it is too tricky we can take care of it after the 18th...

**Comment by tokland** [comment]
In webentry (jquery) we render a table and get its size. If it doesn't fit on the screen, we split the data and re-render again.  Doing this kind of thing with React is very, very ugly, so in this first version I have kept it simple: tables are split to a max of N columns (N=10). If that's not enough, we can try to implement the hacky code.
