### ISSUE TITLE
Depending on the project chosen in step 1 an organization unit is selected on step 3

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dataset-configuration#149]
For instance, Horn of Africa when choosing AFFM1502 (DEVCO Regional AUP)

Is this done on purpose? Something we discussed and I don't remember @tokland

**Comment by adrianq** [comment]
I am testing on dev branch

**Comment by tokland** [comment]
Yes, that's the behaviour from the beginning, we copy the project's orgUnits to the dataset:

https://github.com/EyeSeeTea/dataset-configuration/blob/development/src/models/DataSetStore.js#L242

http://dev.eyeseetea.com:8080/dhis-web-maintenance/#/edit/categorySection/categoryOption/gspzyttMOzN

**Comment by adrianq** [comment]
Yep, you are right. I was confused because the Org Unit was not a country but a continent. Sorry, too many things to keep in mind for me. I am creating a document to start writing down the business logic.
