### ISSUE TITLE
Feedback improvements

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dataset-configuration#159]
- [x]  Implement multilanguage
- [x] Add github module to package
- [x] Add dhis2 module to package
(Extract as npm package -> NOT FOR NOW)
- [x] Add spinner when screenshot is being taken (also on posting issue/messages). Added in the upper-left corner, model window has to be closed to take snapshot.
- [x] Provide link to issue/waffle
- [x] Allows to define issue title
- [x] Integrate with DC app
- [ ] Integrate with user app

**Comment by tokland** [comment]
While we previously used JoeyAndres/feedback-tool, I've checked ivoviz/feedback and I think it would better fit our needs. First, you install it as a normal node package (no with dist files to be installed in include/). The interface is much simpler, no highlight/shadowing, no next/previous, just write the message and send.  What do you think, @adrianq ?

![Screenshot from 2018-04-13 11-31-56.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57022c2f494d000e00432e8e/125516c66e82c728ace21e0d46db978826878dba87e6ab03a24fff99691477227149f37f3dd4b068ee1336525e424baa53444d04bea6d37ef5f22e7a98590cbf80385e70946b44abb0d41bbe52ba21894f83bebe8e5edcfa7f74b9dfd0126754505a9bf54f34a7934acd5af54de04f54a0143261e1647b.png)

**Comment by tokland** [comment]
Let's validate the changes with dataset-configuration, and later do the same for user-app.

![Screenshot from 2018-04-16 13-43-04.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57022c2f494d000e00432e8e/125516c66e82c728ace21e0d46db978826878dba87e6ab03a24fff99691477227149f37f3dd4b568ee1136555c424ea853444d04bea6d37ef5f22e7a98590cbf80385e70946b44abb0d41bbe52ba21894f83bebe8e5edcfa7f74b9dfd0126754505a9bf54f34a7934acd5af543e6445ca515356ae2647b.png)
![Screenshot from 2018-04-16 13-43-25.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57022c2f494d000e00432e8e/125516c66e82c728ace21e0d46db978826878dba87e6ab03a24fff99691477227149f37f3dd4b568ee1136555c424ca953444d04bea6d37ef5f22e7a98590cbf80385e70946b44abb0d41bbe52ba21894f83bebe8e5edcfa7f74b9dfd0126754505a9bf54f34a8934acd5af543e6445ca5153263ee647b.png)
![Screenshot from 2018-04-16 13-43-39.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57022c2f494d000e00432e8e/125516c66e82c728ace21e0d46db978826878dba87e6ab03a24fff99691477227149f37f3dd4b568ee1136555c424da553444d04bea6d37ef5f22e7a98590cbf80385e70946b44abb0d41bbe52ba21894f83bebe8e5edcfa7f74b9dfd0126754505a9bf54f34a8934acd5af543e6445ca515356ae6647b.png)
