### ISSUE TITLE
Investigate custom form and sections as tabs

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dataset-configuration#16]
This task can be split into two parts:
- Implement the concept of subsections. Dhis2 team doesn't like this idea so we will have to come up with a workaround. We would like to have sections displayed as tabs and subsections (displayed as tables) inside that group the dataelements.
- Provide an easy way to implement this in the wizard.

Document containing the original css discussion with the old requirements. These requirements do not apply anymore but there can be something useful for the future:
https://docs.google.com/document/d/1E0nYBJWsLnrFdhbtIELArwQu52O0boruML69D5G3luk/edit#heading=h.gjdgxs

Alternatives discussed so far:
- Alternative 1
Add css classes for the sections in the autoform so we can afterwards apply some js/css to modify the look and feel. Css classes should look like "sectionform-[component]" and "sectionform-[uid]-[component]". Examples: sectionform-title and sectionform-Q3RT-title. This requires changes in velocity templates -> sectionForm.vm

Using the 'Custom JS/CSS' dhis2 app (https://www.dhis2.org/appstore & https://github.com/msf-ocba/dhis_custom_js_css) modify the 'subsections'

As we won't have the concept of subsection we will have to implement a workaround (create sections with a particular format?) so that we can it identify with jquery/css later on.

At the beginning we thought we could only interact with the css. These are some link about creating tabs just using css. Do not think they are useful but just in case:
http://stackoverflow.com/questions/8708347/how-to-make-ul-tabs-with-only-html-css
https://css-tricks.com/functional-css-tabs-revisited/

- Alternative 2
Create sections concept in the right side panel of custom forms. Dhis2 is also happy to accept the  concept of sectiongroup. Section group will be displayed as tabs. 
Pointers to some code: 
   - Velocity Manager
   - DefaultDataEntryFormService -> prepareDataEntry

- Alternative 3
Create custom form on-the-fly. Seems we can embed the html inside the API call.
This is an [example](https://github.com/EyeSeeTea/dataset-configuration/files/883875/customForm.txt) of a custom form. Uploaded as txt as GitHub doesn't allow attaching html files.

Ideas:
- We would like to avoid custom forms as much as possible
- To create the subsections
   - Subsection can be a data element attribute
   - Subsections can be created in a graphical wizard, kind of drag&dop wizard
- We would like not to force the user to interact with the custom form GUI

**Comment by adrianq** [comment]
Interesting links:
https://play.dhis2.org/demo/api/26/dataSets/lyLU2wR22tC?fields=id,displayName,dataEntryForm%5Bid,style,htmlCode%5D,indicators%5Bid,displayName%5D

Theoretically: custom forms doesn't work properly on mobile devices

**Comment by tokland** [comment]
[What I sent you by email, let's keep record]

* dataset-configuration/dhis-web-maintenance: How to implement subsections in the database. Alternative 2: DHIS2 team would add the concept of SectionGroup. For alternatives 1 & 3, in which we don't have the concept of subsection in DHIS, we have two options:

 1. Use data element group sets:

   - Create a DataElementGroupSet called "Subsection" with flag compulsory=TRUE (so it appears in the DataElement form). 
   - Create one DataElementGroup for each subsection. Examples: "EDUCATION - Primary", "CAMP MANAGEMENT - Security", and so no. Those DEG have no DataElements nor Indicators, they are used just as tags.
   - In the DataElement form, select the appropiate subsection in the new selector "Subsection"

   Problem: there is no way to prevent the user from selecting a subsection for a DataElement outside its section (core competency).

2. Split every core competency (a DataElementGroup) as N subsections. For example, EDUCATION would not exist anymore and would be split in N new sections, i.e: "EDUCATION - Primary" and "EDUCATION - Secondary", each with its own DataElements. In this case there DB inconsistency is not possible. We would join sections by its prefix.

* dhis-web-dataentry

Alternative 1: 

- Use DHIS2 application customJS/CSS to inject code (pretty simple, < 100 lines) to join subsections in a single tab as tables. 
- Screenshot: See attachment.

Alternative 3:

- Get the auto-generated HTML form for a dataset (http://SERVER/dhis-web-dataentry/loadForm.action?dataSetId=ID) once it's saved.
- 1) Add JS code to that HTML that joins subsections and adds the accordion (same as alternative1) 
- 2) Update the HTML at this point to join subsections (more user-friendly)
- Save this HTML as custom form of the dataset.

**Comment by adrianq** [comment]
Implementation will be done in #72
