### ISSUE TITLE
Data Entry layout doesn't display properly

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dataset-configuration#165]
![Screenshot from 2017-10-30 11-46-21.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/537c7e24ebef97b1f959e61a/125516c66e82c728ace21e0d46db978826878dba87e6ab03a24fff99691477227e49f27b3dd6b368ee13365559424cad53444d04bea6d37ef5f22e7a98590cbf80385e70946b44abb0d41bbe52ba21894f83bebe8e5edcfa7f74b9dfd0126754505a9bf54f34a7934acd58ff48e74957a21b3060e0647b.png)

**Comment by adrianq** [comment]
@tokland does dev.est contain the latest css/js?

**Comment by tokland** [comment]
It looks like a textarea, right, I'll check how chrome render thems.

**Comment by tokland** [comment]
Firefox shows it correctly, but chrome seems to render the textarea first and later use a bigger width, so it's moved. Setting a `max-width` on those textarea seems to work, not sure if it's the best solution. Tested in dev.est. I'll open a PR.

![Uploading Screenshot from 2017-10-30 13-29-56.png…]()

**Comment by adrianq** [comment]
Thanks for the quick fix!
