### ISSUE TITLE
Add Status Column in Section 4

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dataset-configuration#171]
- [x] Add dataElement/indicator group set for status in settings
- [x] Hide Inactive
- [x] Sort first Active and then Phased Out
- [x] Highlight somehow phased out dataelement (darker background in the row, highlight 'phased out' label, etc)

**Comment by tokland** [comment]
Proposal for highlighting:

![Screenshot from 2017-11-07 13-02-13.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57022c2f494d000e00432e8e/125516c66e82c728ace21e0d46db978826878dba87e6ab03a24fff99691477227e49f27a3dd5b468ee1136515d424faf53444d04bea6d37ef5f22e7a98590cbf80385e70946b44abb0d41bbe52ba21894f83bebe8e5edcfa7f74b9dfd0126754505a9bf54f34a9934acd59f64be44b54a2163e6be1647b.png)
