### ISSUE TITLE
Fourth step (Manage DataSet Sections)

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dataset-configuration#18]
- [x] Create Interface.
   - [x] Investigate current components in dhis graphical interfaces library to decide what would be the best strategy. This is somehow a tradeoff between UX and reusability
   - [x] It would be ideal to provide a single page interface. An accordion set of panel interface in which each panel corresponds to a section could be an option.
   - [x]  We would like to provide filters for dataelements/indicator per core competency and origin
   - [x] We would like to provide sorting per column

- [ ] Logic

   - [ ] Generate List of Sections based on Competencies from the first step. For each competency (data element group) we create two section: [Competency name] and  [Competency name] (B). 

   - [ ] [Competency name] section should contain all ‘output’ Data Element for that data element group. 
   - [ ] [Competency name] (B) section should contain all ‘outcome’ Indicator for that data element group (core competency). 
      - [ ] We will have to extract all dataelements from num and den. Just the first element of any UID.UID2.UID3.
      - [ ] For every indicator we will get the code and create a string like: [indicator_code] + "-C" . We will look for a data element with this code. Application should not fail if this data element can not be found.
Example:
Indicator:
GL-EB1A: % of enrolled learners who pass the final YEP program exam
Data Element:
GL-EB1A-C: comment: % of enrolled learners who pass the final YEP program exam
      - [ ] We will be adding as well the indicators to the dataset

   - [ ] Users should be allowed to select/unselect data elements/indicators per section. By default just ‘Global/Mandatory’ data elements/indicators are selected. DataElementOrigin defined the scope-> Global or Donor or Local/Country or... 

   - [ ] Users can also set Row Totals and Column Total per section

**Comment by adrianq** [comment]
Doubts:
- [ ] For outcome we should also add indicators to the datasets
- [ ] We said sth about adding the comment of the indicator but cannot remember

**Comment by adrianq** [comment]
Updating the card with the information discussed with the client:
- For every indicator we will get the code and create a string like: [indicator_code] + "-C" . We will look for a data element with this code. Application should not fail if this data element can not be found.
Example:
Indicator:
GL-EB1A: % of enrolled learners who pass the final YEP program exam
Data Element:
GL-EB1A-C: comment: % of enrolled learners who pass the final YEP program exam
- We will be adding as well the indicators to the dataset
- We can assume there is going to be a one-to-one mapping between a data element and an indicator. This will simplify hugely the edit feature. We can start with this assumption for now.

**Comment by tokland** [comment]
Mockup to show the client:

-[ ] Sidebar left / Tab right-top (+ section all), using material-ui-scrollable-tabs
-[ ] Take tables from maintenance-app with search, no pagination.
-[ ] Order by columns (asc/desc, single column sorting)
-[ ] Tabs/Sidebar see maint styles
-[ ] When ALL, show in table column Subsection, after NAME
-[ ] Cell: tooltip with full text.
-[ ] sidebar: prop expandable
-[ ] when NOT expanded, show current section. 
-[ ] Table: Cell (header/data) with arbitrary content: Enabled rows -> attribute -> keep on resize
-[ ] Filter by some columns: i.e. Origin (with dropdown)

**Comment by tokland** [comment]
Mockup prepared. Code pushed and deployed: http://dev.eyeseetea.com:8080/api/apps/dataset-configuration/index.html#/datasets/add

**Comment by tokland** [comment]
A dataset has two ways to associate data elements. One is through the sections, the other through dataSetElement (that is the multi-select you get on the form add/edit), which is a dataElement + categoryCombo (btw, i don't see why we need this intermediate dataSetElement, a dataElement already has a categoryCombo, maybe legacy reasons?).  Here, do we need to populate dataset.dataSetElements or only the dataelements within sections?

Example of the structure and to show that the associated data elements are independent:
```
> $r.state.modelToEdit.sections.toArray()[0].dataElements.toArray().map(de => de.displayName)
(2) ["GL-E100/C: # of instiutions receiving vouchers", "GL-E94/C: # of indviduals receiving vouchers"]
> $r.state.modelToEdit.dataSetElements.map(dse => dse.dataElement.displayName)
["CO-E14: # of new FEM developed and implemented"]
```

**Comment by tokland** [comment]
Pushed the changes on the PR. Ready to test.  When I enabled all core competencies, I was unable to save the dataset since some datalements were repeated in different sections. I've added coded to show an error message with the problem, I think it's better than silently remove duplicates. Example of errors:

```
DataElement[id=GL-LB1A/HH-C: comment: % beneficiary HH's who report exercising HLP rights] used in multiple sections: ICLA (B),SHELTER (B)
DataElement[id=GL-LB1A/HH-D: # of beneficiary HH's who receive (Information, counselling and/or legal assistance) services] used in multiple sections: ICLA (B),SHELTER (B)
DataElement[id=GL-LB1A/HH-N: # beneficiary HH's who report exercising HLP rights] used in multiple sections: ICLA (B),SHELTER (B)
DataElement[id=GL-LB1B/HH-C: comment: % beneficiary HH's who report possessing a document for house/land/property] used in multiple sections: ICLA (B),SHELTER (B)
`` `
