### ISSUE TITLE
Reorganise Configuration Setting

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dataset-configuration#183]
Tabs:

- General: Project category, category combination, CC, Country, expiry date (see new issue).
- Sections: (groups with Paper). Group1: Theme (2), Group attribute (1). Group 2: all the rest

**Comment by tokland** [comment]
Proposal:

![Screenshot from 2017-11-20 13-46-19.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57022c2f494d000e00432e8e/125516c66e82c728ace21e0d46db978826878dba87e6ab03a24fff99691477227e49f27a3dd7b368ee11365559424fa553444d04bea6d37ef5f22e7a98590cbf80385e70946b44abb0d41bbe52ba21894f83bebe8e5edcfa7f74b9dfd0126754505a9bf54f34a8934acd59f74ae94c5ca3113060e5647b.png)

**Comment by adrianq** [comment]
Looks good to me!
