### ISSUE TITLE
Global Indicator not selected on init

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dataset-configuration#185]
In Education Outcome, some 'Active Indicators (All)' at the top but a couple of them also at the bottom of the list.

**Comment by tokland** [comment]
Sorry, I hadn't seen the second point. It works according to the notes I have:

selected -> non-phase-out -> name

Do we want a full ordering by status?

**Comment by adrianq** [comment]
This is what I am getting (no change performed). Your ordering is fine but shouldn't we select Global Indicator on init?
![screenshot from 2017-11-14 22-53-56](https://user-images.githubusercontent.com/6850223/32809522-0314c388-c98f-11e7-95ec-0e1368f6ff9e.png)
![screenshot from 2017-11-14 22-54-18](https://user-images.githubusercontent.com/6850223/32809525-059b59f0-c98f-11e7-8b20-4e6bf6d5c7b7.png)

**Comment by adrianq** [comment]
I have just renamed the issue accordingly. Sorry for the confusion with the sorting thing

**Comment by tokland** [comment]
That's indeed a bug, I'll send a PR.
