### ISSUE TITLE
Display a proper message when a DE is found in more than one section

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dataset-configuration#187]
Check Snackbar (multiline) or feedback  (up)

**Comment by tokland** [comment]
Using snackbar with multiline (limited to 10 entries) would look like this. What do you think, @adrianq ?

![Screenshot from 2017-11-20 12-10-39.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57022c2f494d000e00432e8e/125516c66e82c728ace21e0d46db978826878dba87e6ab03a24fff99691477227e49f27a3dd7b368ee1036505f424da553444d04bea6d37ef5f22e7a98590cbf80385e70946b44abb0d41bbe52ba21894f83bebe8e5edcfa7f74b9dfd0126754505a9bf54f34a7934acd59f74ae64b57a7143e64e7647b.png)

**Comment by adrianq** [comment]
@tokland I know it is a bit late but it looks good to me as well. Just one thing, can we change the string in the PR to say something like 'Please contact the Dhis2 Administrator with this error' or something like that?

**Comment by tokland** [comment]
Sure, pushed:

![screenshot from 2017-11-20 13-36-05](https://user-images.githubusercontent.com/24643/33018700-be4f2b4a-cdf7-11e7-81d0-82a0d8a9f0d5.png)
