### ISSUE TITLE
"expiry days" refactor

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dataset-configuration#188]
- [x] Add default 'expiry days' to the admin panel
- [x] Set value by default to the one in the admin panel.
- [x] Add help to 'expiry days' explaining this field in step 2.

**Comment by tokland** [comment]
![Screenshot from 2017-11-21 12-41-32.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57022c2f494d000e00432e8e/125516c66e82c728ace21e0d46db978826878dba87e6ab03a24fff99691477227e49f27a3dd7b268ee1036555e424dae53444d04bea6d37ef5f22e7a98590cbf80385e70946b44abb0d41bbe52ba21894f83bebe8e5edcfa7f74b9dfd0126754505a9bf54f37a0934acd59f749e74951ad113e66e2647b.png)
