### ISSUE TITLE
Delay on Data Entry

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dataset-configuration#192]
It takes a bit more than expected (2 secs) when introducing a value and tabbing from one field to another. 

See https://github.com/EyeSeeTea/dataset-configuration-blessed/issues/71

It may have to do with multiple sections?

**Comment by tokland** [comment]
We can close this, see:

https://github.com/EyeSeeTea/dataset-configuration-blessed/issues/71#issuecomment-346782669
