### ISSUE TITLE
Looks like there are some hidden labels when hovering in Dissagregation step (no permissions)

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dataset-configuration#200]
![screenshot from 2017-11-29 22-14-42](https://user-images.githubusercontent.com/6850223/33401961-06889ad8-d553-11e7-9dfa-34ccb721d6b5.png)

**Comment by tokland** [comment]
That was weird because the right panel is not even rendered. Now I see what's happening, it's the hovering of the DE category option text, which uses a div. With a span it will show up only when hovering over the text.
