### ISSUE TITLE
Seventh step (Sharing)

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dataset-configuration#21]
Create Interface
 - [x] Dropdown list to choose the country (prefill with user group the user belongs to-> [country_prefix]_users

Logic
 - [x] Dataset Disaggregation (catCombos created on the fly) -> Share with all the users in the country [COUNTRY_PREFIX]_users
 - [x] Add datasets to user role -> [COUNTRY_PREFIX]__dataset_[COMPETENCY]
- [x] Add Sharing dataset ->
[COUNTRY_PREFIX]_users -> view
[COUNTRY_PREFIX]_admin -> edit
gl_admin -> edit

I have added the logic here although this will obviously happen in the last step

**Comment by tokland** [comment]
User group _gl_admin_ does not exist, there are those 3: GL_AllAdmin, GL_GlobalAdministrator, GL_UserAdmin.

http://dev.eyeseetea.com:8080/api/userGroups.json?filter=name:ilike:admin&fields=name
