### ISSUE TITLE
Settings Panel

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dataset-configuration#23]
- [x] Create user rol for app admin
- [x] Add all configurable parameters as dropdown components
- [x] @adrianq to confirm we can use code instead of uid (yes, we can). But since we have a dropdown with names, we can still save uids.

**Comment by tokland** [comment]
Found an issue in d2, reported bug and sent a PR: 

https://github.com/dhis2/d2/issues/130
https://github.com/dhis2/d2/pull/131
