### ISSUE TITLE
Entry rows width improvements

### ISSUE THREAD

**Issue by tokland** [EyeSeeTea/dataset-configuration#236]
Limit data element title column to 50%, render in multi-line in this case and use the other 50% for data columns.

**Comment by tokland** [comment]
While testing I've seen that the problem is not really the width of the data element but the split.  The example of Troyel:

https://camo.githubusercontent.com/15e19a19ec4e204881585177002970038b2c4c75/68747470733a2f2f776166666c65696f2d6469726563742d75706c6f6164732d70726f64756374696f6e2e73332e616d617a6f6e6177732e636f6d2f75706c6f6164732f3539306336333461643133643762303032303661373732312f313235353136633636653832633732386163653231653064343663623963383832633866383665393862666262653534616435336637643432623437323337663330343665663639363039376563323262613431366634333535346434626134313235643537313561616665383037616637623033633231386135633039626564333639306537306332336330336230616163303465653135356535376464323035643066346165383035656331653033373234653238613861346233633139303731623839666235653337623264342e504e47

The problem here is that with no split, even if the data element column takes only 71px, there is no room for all the data values. So it decides to split (that's what the screenshot shows), and just a one-level split results in one table per IDP-Male/Famale, one for Regufee-Male/Female, etc. 

I'd say that it makes more sense to refactor the split. Idea: Maybe split columns evenly, regardless of the catcombos, in 2 parts/3/4/... until it fits. The code will be a more complex, but we'll have the limitations we are seeing. In this case, 2 sub-parts should be enough for rendering within the viewport.

**Comment by adrianq** [comment]
Closing this one for now. As discussed with @tokland  it looks like refactor by columns regardless of catcombos will make things more complicated for the users. As it looks like it is not a critical issue for them I am just closing it for the moment
