### ISSUE TITLE
Add logs mechanism

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dataset-configuration#265]
- [x] Logged Actions: create and any contextual action
- [x] Implement UI
- [x] Implement backend logic

**Comment by adrianq** [comment]
For reference:
https://github.com/EyeSeeTea/dataset-recoding
End point in dataset recoding - > http://dev.eyeseetea.com:8080/api/dataStore/dataset-recoding/logging-bucket-0
Dhis2 doc -> https://docs.dhis2.org/2.26/en/developer/html/webapi_data_store.html
Deployed App -> http://dev.eyeseetea.com:8080/api/apps/dataset-recoding-dhis2-app

**Comment by jordibc** [comment]
Also document: https://docs.google.com/document/d/1BED4QKxkAYbvgl3tFvG8Yr0xpC9cZ1xtAnjtR7QAcPw/edit#heading=h.3ecsjlyzlrz5
