### ISSUE TITLE
Add an attribute or whatever to distinguish between datasets created by dataset configuration app

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dataset-configuration#266]
- [x] Add the attribute locally and drop a comment
- [x] Add attribute to settings
- [x] Set attribute to true on DC app save
- [x] Update documentation
- [ ] Ask NRC to create the attribute on GORS
- [ ] Ask NRC to update previously created datasets

**Comment by tokland** [comment]
Only client-related tasks pending. 

Name: Created by Dataset Configuration
Code: GL_CREATED_BY_DATASET_CONFIGURATION
Value Type: Yes/No
Models: Data set

![Screenshot from 2018-05-23 09-11-25.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57022c2f494d000e00432e8e/125516c66e82c728ace21e0d46db978826878dba87e6ab03a24fff99691477227149f37e3dd7b068ef1b36505e424ca953444d04bea6d37ef5f22e7a98590cbf80385e70946b44abb0d41bbe52ba21894f83bebe8e5edcfa7f74b9dfd0126754505a9bf54f34a9934acd5af14be44450a010376be3647b.png)
