### ISSUE TITLE
Explore if we can customise select all in org unit selection

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dataset-configuration#286]
At the moment, first OU is selected on init and 'select all' applies selection only for OU within this one. 
How to test it-> host: gors user: Test

**Comment by tokland** [comment]
I see 2 approaches:

1. Make the current container (the one with a grey background) unselectable. When no orgunit is selected as container, the message "For organisation units within [...]" would instead say "For all user organisation units" and the actions would apply to all visible orgunits in the tree.

2. Show orgunits parents in the tree until you get to a common root. This way you can select the container root and apply actions to all (visible) children. Those new rendered roots  are visible and its container selectable, but not selectable (no chekbox), as they don't belong to the user.

Neither of those two solutions is trivial (I'd say both have more or less similar coding effort), the main tree component and select all/bylevel/bygroup must be modified in d2-ui.

**Comment by tokland** [comment]
Try this:

- Link "(select all)" -> select all visible orgUnits

**Comment by tokland** [comment]
No changes on the app are required, only in d2-ui: https://github.com/EyeSeeTea/d2-ui/pull/19
