### ISSUE TITLE
Modify feedback tool to send a Dhis2 Internal message

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dataset-configuration#291]
See https://waffle.io/EyeSeeTea/dataset-configuration-blessed/cards/5aa11ffa3d438c001bc06964 and https://waffle.io/EyeSeeTea/dataset-configuration-blessed/cards/5ab202caa5942d001d01edfc for further information

**Comment by tokland** [comment]
Done, just waiting for confirmation of userGroup. Config looks something like:

`{
  createIssue: false,
  sendToDhis2UserGroups: ["GL_GlobalAdministrator"],
}`

For simplicity, I am keeping markdown also on dhis2 message, it also makes simpler to finally report a github issue, as it is copy&paste:

![Screenshot from 2018-03-21 12-13-51.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57022c2f494d000e00432e8e/125516c66e82c728ace21e0d46db978826878dba87e6ab03a24fff99691477227149f3783dd7b268ee1036505c424bad53444d04bea6d37ef5f22e7a98590cbf80385e70946b44abb0d41bbe52ba21894f83bebe8e5edcfa7f74b9dfd0126754505a9bf54f34a7934acd5af74de24d5ca4103661e4647b.png)
