### ISSUE TITLE
Send message to feedback admin with error trace on save error

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dataset-configuration#300]

**Comment by tokland** [comment]
Now that I think of it, instead of a button, we could send the message automatically so we don't depend on the user. Recipients: the same that receive user feedback: `sendToDhis2UserGroups: ["GL_GlobalAdministrator", "GL_LocalindicatorAdmin"]`

**Comment by adrianq** [comment]
Every time an error like this happens you meant? If so, it sounds good to me :)

**Comment by tokland** [comment]
Ok! (Yes, on any error in the save process)

**Comment by tokland** [comment]
Other savings (orgunits assign, sharing, ...) perform ajax calls outside our infrastructure,  so the d2-ui components should be modified if we want that.
