### ISSUE TITLE
Strange character on feedback textarea

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dataset-configuration#303]
![Screenshot from 2018-04-11 14-52-37.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/537c7e24ebef97b1f959e61a/125516c66e82c728ace21e0d46db978826878dba87e6ab03a24fff99691477227149f37f3dd4b268ee1636545d424dab53444d04bea6d37ef5f22e7a98590cbf80385e70946b44abb0d41bbe52ba21894f83bebe8e5edcfa7f74b9dfd0126754505a9bf54f34a6934acd5af54fe4495da6113667e2647b.png)

**Comment by tokland** [comment]
It's an artifact of the extension Grammarly:

![Screenshot from 2018-04-12 11-54-22.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57022c2f494d000e00432e8e/125516c66e82c728ace21e0d46db978826878dba87e6ab03a24fff99691477227149f37f3dd4b168ee1336545b424cae53444d04bea6d37ef5f22e7a98590cbf80385e70946b44abb0d41bbe52ba21894f83bebe8e5edcfa7f74b9dfd0126754505a9bf54f34a7934acd5af54ee34b5ca6173365e1647b.png)

**Comment by adrianq** [comment]
Oh shit! Sorry about that. At least you also had it and were able to reproduce the artifact. Thanks!
