### ISSUE TITLE
Analyse how the data set is presented, as well as printing or downloading form options

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dataset-configuration#309]

**Comment by tokland** [comment]
Technical details:
Endpoint (example): http://localhost:9026/api/26/pdfForm/dataSet/NXCZRu5Hsbg
Controller: dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/PdfFormController.java
PDF generator service: dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/pdfform/DefaultPdfDataEntryFormService.java

The PDF is auto-generated, the custom form HTML is not used. 

Sections are shown, but custom concepts as themes/groups are not. An example:

[JOFM1618 (Swiss Confederation) 2018-04-13.pdf](https://github.com/EyeSeeTea/dataset-configuration/files/1907218/JOFM1618.Swiss.Confederation.2018-04-13.pdf)

**Comment by adrianq** [comment]
I talked to them about this and they are not using this functionality. Whenever they want to print the data set (which is not particularly often) they just print it from the data entry app so it has the right look&feel.
