### ISSUE TITLE
Improve localization

### ISSUE THREAD

**Issue by tokland** [EyeSeeTea/dataset-configuration#316]
- [x] UI: InitialConfig
- [x] UI: GeneralInformation
- [x] UI: Sections
- [x] UI: Disaggregation
- [x] UI: Grey fields
- [x] Use translations in custom form.

**Comment by adrianq** [comment]
@tokland I have just merged this PR. Just one thing, can you please update the documentation? If you can briefly explain how we generate the custom form (I think we have a custom form section). Feel fre to close this card once you are done! Thanks!

**Comment by tokland** [comment]
Done.
