### ISSUE TITLE
Analyse why in Data Entry for the group we are showing only the code but the group description

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dataset-configuration#319]

**Comment by tokland** [comment]
I think Troyel asked for the indicator.code to be shown, but we can simply change the field to whatever we want (i.e displayName).

code:

![Screenshot from 2018-05-17 10-30-47.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57022c2f494d000e00432e8e/125516c66e82c728ace21e0d46db978826878dba87e6ab03a24fff99691477227149f37e3dd4b468ee1236525f424aab53444d04bea6d37ef5f22e7a98590cbf80385e70946b44abb0d41bbe52ba21894f83bebe8e5edcfa7f74b9dfd0126754505a9bf54f34a7934acd5af04ee54b57ac11356ae0647b.png)

displayName:

![Screenshot from 2018-05-17 10-34-24.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57022c2f494d000e00432e8e/125516c66e82c728ace21e0d46db978826878dba87e6ab03a24fff99691477227149f37e3dd4b468ee1236525b424ca853444d04bea6d37ef5f22e7a98590cbf80385e70946b44abb0d41bbe52ba21894f83bebe8e5edcfa7f74b9dfd0126754505a9bf54f34a8934acd5af04ee54b57ac113562e0647b.png)

**Comment by tokland** [comment]
- [ ] Use displayName for groups
