### ISSUE TITLE
Review if this needs to be included in webpack exclude: /node_modules\/(?!(d2-ui)\/).*/

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dataset-configuration#365]

**Comment by tokland** [comment]
I don't think a `/node_modules\/(?!(d2-ui)\/).*/  exclusion rule is necessary. Both using d2-ui as a normal package (from github) or a "yarn/npm link",  `node_modules/d2-ui/lib` code is ES5 commonjs, so we don't need Babel to apply transformations there. 

Please, reopen if the reason for the opening was different.

Note: while checking this issue, I saw a problem with the yarn.lock, here is the fix:

https://github.com/EyeSeeTea/dataset-configuration/pull/375
