### ISSUE TITLE
pre-selected output and outcome open and close dates.

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dataset-configuration#397]
The open dates, for example, could be beginning of each year (unless project starts sometime during the year) and the output close dates could be 1st April every year and outcome close dates could be 1st May every year.

**Comment by tokland** [comment]
![dataset-configuration-dates](https://user-images.githubusercontent.com/24643/60651716-1002db00-9e47-11e9-9546-69e8281e8629.png)
