### ISSUE TITLE
Test Dataset Configuration in a DHIS2 2.31

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dataset-configuration#407]
- [x] Use gors.nrc.no_db_dhis2_2.26-bba49cc_20190329T033203Z.sql
- [x] Migrate 2.27 -> 2.31 (document)
- [x] Deploy to dev2:8080
- [x] Test the app

**Comment by tokland** [comment]
A migration from DHIS2 version A to C requires performing the intermediate migrations (A -> B and B -> C). For each of them:

- Run the migration SQL script (if specified in the migration notes of that version).
- Start a DHIS2 instance using the WAR for that specific versions (Ex: https://releases.dhis2.org/2.28/dhis.war)

Notes:

- DHIS2 2.26 could run on postgres 9.5, but newer versions require 9.6 or higher, although version 10 is recommended. In our tests, **we used postgres 10.7**.

Check migration release notes here:

https://www.dhis2.org/downloads -> WAR file -> Upgrade notes

Note that there are some migrations scripts for 2.29 and 2.30, which should be run manually before starting the corresponding WAR file:

https://github.com/dhis2/dhis2-releases/blob/master/releases/2.29/upgrade-229.sql
https://github.com/dhis2/dhis2-releases/blob/master/releases/2.30/upgrade-230.sql

Example (assuming db name `nrc231`):

```
$ cat upgrade-230.sql | psql nrc231
```

- On migration 2.26 -> 2.27: we got this error:

```
* INFO  2019-10-31 10:50:28,794 Executing startup routine [8 of 15, runlevel 7]: TrackedEntityTableAlteror (DefaultStartupRoutineExecutor.java [main])
* ERROR 2019-10-31 10:50:29,437 org.springframework.dao.DuplicateKeyException: StatementCallback; SQL [INSERT INTO trackedentity(trackedentityid,uid, code, created, lastupdated,name, description) values(nextval('hibernate_sequence'),'MCPQUTHX1Ze','Person','2019-10-31','2019-10-31','Person','Person')]; ERROR: duplicate key value violates unique constraint "uk_b0aojuanxabfuylrbc2k6xk20"
  Detail: Key (name)=(Person) already exists.; nested exception is org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "uk_b0aojuanxabfuylrbc2k6xk20"
  Detail: Key (name)=(Person) already exists.
```

It happened to other people: http://dhis-developers-list.1563109.n2.nabble.com/latest-2-28-build-not-working-td7613565.html

Their solution (which also worked in our tests), was setting the hardcoded ID the migration expects:

```
psql# update trackedentity set (uid,code,name,description)=('MCPQUTHX1Ze','Person','Person','Person') where name='Person';
UPDATE 1
```
- 2.30 -> 2.31: We must delete the SQL views before:
  - http://localhost:9030/dhis-web-data-administration/index.html#/maintenance
  - Select "Drop SQL Views"
  - Perform maintenance

**Comment by tokland** [comment]
App testing:

- Listing (column sorting, filter, only my own) OK
- Settings (show, update) OK
- New dataset OK
- logs OK
- Edit dataset -> FAIL to update orgUnits with importStragy=MERGE (if REPLACE, problems with save, to study)
- Contextual:
    - Details. OK
    - Sharing (show, update) OK
    - Delete dataset. OK
    - Assign to orgunits (single, multiple; merge/replace strategies) -> FAIL with d2-ui-ds importStrategy=MERGE
    - Clone

**Comment by tokland** [comment]
- [ ] Check if possible (and implement) use of sharing modal from metadata-sync
