### ISSUE TITLE
Refactor loginurl redirection

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dataset-configuration#58]
From the [PR](https://github.com/EyeSeeTea/dataset-configuration/pull/56)

we have this redirection to loginUrl here and in redirectToLogin method. The url path and the code that makes the redirection is redundant. Can we maybe extract this redirection method into an utils function? Then in the sessiondialog, redirectToLogin doesn't need to be a method hardcoded but a property that we pass to the component SessionDialog. What do u think?

**Comment by tokland** [comment]
Yes, that makes sense.
