### ISSUE TITLE
Eighth step (save)

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dataset-configuration#60]
Create Interface
 - [x] Summary what we have just created (send also warnings/non-fatal errors, i.e. userRole not found)

Notification
 - [x] Send message to GL_M&E group.
 - [x] Send message to [COUNTRY_PREFIX]_M&E_DatasetCompleted
Message should be something like: “New data set created, [name] by [username]”
 - [x] Send special notificacion if dataset couldn’t be added to user role.
- [x] Add org units to project ( do not overwrite but append)

**Comment by tokland** [comment]
Example of creation message:

![d2-message-creation.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57022c2f494d000e00432e8e/125516c66e82c728ace21e0d46ecc6d72e8790ba8eeeba0ea74ff5953d4f287d6b48e13b628ae92dbc56395b4d5a49fe100d5e40aeafdc2caee03871d95c0aefd16b5776c22f0dbefad341eb5ee779c11ac7a4b6984ec6e23c20e78a8f493c1f001181f85827ed.png)

Example of warnings message:
![d2-message-warning.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57022c2f494d000e00432e8e/125516c66e82c728ace21e0d46ecc6d72e8790ba8eeeba0eb35ce29a204820316546b3397f8fe62bab0021435a581cfd14595b16aaac8e23f0b23d238a5d09edd7655d70d42103eee9dc4be05ce36ade0d97bcae884acae93825e68b894d3f19071a8afa4f78.png
