### ISSUE TITLE
Add Custom/Js app to dev-est

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dataset-configuration#61]
Add css attached

**Comment by adrianq** [comment]
[CSS GORS 220617.txt](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/537c7e24ebef97b1f959e61a/125516c66e82c728ace21e0d46cba7a963a5ac9bbca9ed11f40ba1c36b0a65633b0ba92e7391a172fd172c030e0a4fa8130e0a43f4af8d2af5b63d728a5a03efd57f4366846c4ff8e7df46f554f832815d87b0b68b48c9e03c26e18c8f49371d070ac4.txt)

**Comment by adrianq** [comment]
We should upload it to somewhere in GitHub. Let's discuss about it

**Comment by tokland** [comment]
- Uploaded to dev.est: http://dev.eyeseetea.com:8080/api/apps/customjscss/index.html#/customcss
- Repo: https://github.com/EyeSeeTea/dataset-configuration/pull/74
