### ISSUE TITLE
Hide code

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dataset-configuration#67]
Hide code in step 2. We will be setting the code if the dataset is linked to a project. Otherwise, we can use the name of the dataset as the code

@adrianq to confirm how to behave if it is a duplicate code

**Comment by adrianq** [comment]
@tokland We have an answer: We will hide the code textfield. We will keep the code empty unless we have a project linked. If we have a project linked we will be using the code we currently generate from the project. e.g Name: AFFM1601 (ECHO Emergency) Code: AFFM1601 Data Set .  We validate if this code is already in use, if so we leave it empty.

Moving the card back to ready

**Comment by tokland** [comment]
In the example:

Project (categoryOption): "AFFM1601 (ECHO Emergency)"
-> Name: "AFFM1601 (ECHO Emergency)"
-> Code: "AFFM1601 Data Set"

Does that mean we have to remove within-parentheses text from the categoryOption name to build the code?
