### ISSUE TITLE
Implement subsections

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dataset-configuration#72]
- [x] Create Data Element Group Set and Indicator Group Set for Theme (when we use to call subsubsection)
- [x] Add Attribute for Subsubsection including indicator and elements. @adrianq to double check with the client what is the desired name
- [x] Implement javascript in custom/js app to reorganise sections and subsubsections
- [x] Modify dataset configuration layout to re-add subsections and subsubsections as columns

**Comment by adrianq** [comment]
I have attached current NRC custom css in #61

**Comment by tokland** [comment]
Some notes:

- DE group set created (and some DE groups to play with) in dev.est, but not Indicator Group Set for Theme, not necessary for now: http://dev.eyeseetea.com:8080/dhis-web-maintenance/#/edit/dataElementSection/dataElementGroupSet/chyJVMF3G7k
- Added attribute for group: http://dev.eyeseetea.com:8080/dhis-web-maintenance/#/edit/otherSection/attribute/YxwyKOlG4lP

![dhis2-ds-config-sections.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57022c2f494d000e00432e8e/125516c66e82c728ace21e0d46ec9c9330d0cead9ca4bc4caa5bf993645522703d0dac2563c7af6aaf50740b0a0c0abe4b4a5a43aea8dc2aa2e46a258d545de9d03e5f75c43d17a4ba860da313f871d51bdaebe5c01982fa3737e48a854e3a170c1b8dfb5c37a09043cc4abb.png)
