### ISSUE TITLE
Add text in Sharing tab

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dataset-configuration#86]
Something like 'Please select the region you want share this dataset with' on top of the drop down list. I am also thinking that maybe we don't need a step for this. I know there is some logic behind the component but potentialy it can go at the bottom of the 'General Information' tab... Let's just add the title for the moment and we can revisit this issue in the future.

**Comment by tokland** [comment]
[feature/step-7-sharing a155edd3] Sharing: Add help message for country selector
